//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlawBOT.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlawBOT.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/CriticalFlaw/FlawBOT/.
        /// </summary>
        internal static string BOT_GITHUB {
            get {
                return ResourceManager.GetString("BOT_GITHUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discordapp.com/oauth2/authorize?client_id=339833029013012483&amp;scope=bot&amp;permissions=66186303.
        /// </summary>
        internal static string BOT_INVITE {
            get {
                return ResourceManager.GetString("BOT_INVITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel with the same name already exists..
        /// </summary>
        internal static string ERR_CHANNEL_EXISTS {
            get {
                return ResourceManager.GetString("ERR_CHANNEL_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be blank or over 100 characters..
        /// </summary>
        internal static string ERR_CHANNEL_NAME {
            get {
                return ResourceManager.GetString("ERR_CHANNEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel topic must be less than 1024 characters long..
        /// </summary>
        internal static string ERR_CHANNEL_TOPIC {
            get {
                return ResourceManager.GetString("ERR_CHANNEL_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid color code. Please enter a HEX color code like #E7B53B..
        /// </summary>
        internal static string ERR_COLOR_INVALID {
            get {
                return ResourceManager.GetString("ERR_COLOR_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reach the Dog.CEO API..
        /// </summary>
        internal static string ERR_DOG_PHOTO {
            get {
                return ResourceManager.GetString("ERR_DOG_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the server emoji. Either the HTTP request failed or Discord prevented the operation from completing..
        /// </summary>
        internal static string ERR_EMOJI_ADD {
            get {
                return ResourceManager.GetString("ERR_EMOJI_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a URL pointing to an emoji image or attach an image..
        /// </summary>
        internal static string ERR_EMOJI_IMAGE {
            get {
                return ResourceManager.GetString("ERR_EMOJI_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server emoji name is invalid..
        /// </summary>
        internal static string ERR_EMOJI_NAME {
            get {
                return ResourceManager.GetString("ERR_EMOJI_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the server emoji. Either the image size was too large..
        /// </summary>
        internal static string ERR_EMOJI_SIZE {
            get {
                return ResourceManager.GetString("ERR_EMOJI_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred: {0} :
        ///{1}.
        /// </summary>
        internal static string ERR_EXCEPTION {
            get {
                return ResourceManager.GetString("ERR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception: {0} :
        ///{1}.
        /// </summary>
        internal static string ERR_EXCEPTION_INNER {
            get {
                return ResourceManager.GetString("ERR_EXCEPTION_INNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address, please follow the format: `174.116.36.120`.
        /// </summary>
        internal static string ERR_INVALID_IP {
            get {
                return ResourceManager.GetString("ERR_INVALID_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection info, please follow the format: `174.116.36.120:27015; password hello`.
        /// </summary>
        internal static string ERR_INVALID_IP_GAME {
            get {
                return ResourceManager.GetString("ERR_INVALID_IP_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calculating math equation, make sure your values are integers and the operation is valid!.
        /// </summary>
        internal static string ERR_MATH_EQUATION {
            get {
                return ResourceManager.GetString("ERR_MATH_EQUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reach the NASA API..
        /// </summary>
        internal static string ERR_NASA_API {
            get {
                return ResourceManager.GetString("ERR_NASA_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a poll question..
        /// </summary>
        internal static string ERR_POLL_QUESTION {
            get {
                return ResourceManager.GetString("ERR_POLL_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide more information on the issue (50 characters minimum)..
        /// </summary>
        internal static string ERR_REPORT_CHAR_LENGTH {
            get {
                return ResourceManager.GetString("ERR_REPORT_CHAR_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an existing server role..
        /// </summary>
        internal static string ERR_ROLE_EXISTING {
            get {
                return ResourceManager.GetString("ERR_ROLE_EXISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name cannot be blank..
        /// </summary>
        internal static string ERR_ROLE_NAME {
            get {
                return ResourceManager.GetString("ERR_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user doesn&apos;t have any roles..
        /// </summary>
        internal static string ERR_ROLE_NONE {
            get {
                return ResourceManager.GetString("ERR_ROLE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unauthorized to remove roles from this user..
        /// </summary>
        internal static string ERR_ROLE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERR_ROLE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find voice channel or you&apos;re not connected....
        /// </summary>
        internal static string ERR_VOICE_CHN_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_VOICE_CHN_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice is not activated.
        /// </summary>
        internal static string ERR_VOICE_NOT_ACTIVE {
            get {
                return ResourceManager.GetString("ERR_VOICE_NOT_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice is not connected in this server.
        /// </summary>
        internal static string ERR_VOICE_NOT_CONNECTED {
            get {
                return ResourceManager.GetString("ERR_VOICE_NOT_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond with **yes** to proceed or wait 10 seconds to cancel this operation..
        /// </summary>
        internal static string INFO_RESPOND {
            get {
                return ResourceManager.GetString("INFO_RESPOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting Down.
        /// </summary>
        internal static string INFO_SHUTDOWN {
            get {
                return ResourceManager.GetString("INFO_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emoji not found in the server list..
        /// </summary>
        internal static string NOT_FOUND_EMOJI {
            get {
                return ResourceManager.GetString("NOT_FOUND_EMOJI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        internal static string NOT_FOUND_GENERIC {
            get {
                return ResourceManager.GetString("NOT_FOUND_GENERIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not found..
        /// </summary>
        internal static string NOT_FOUND_LOCATION {
            get {
                return ResourceManager.GetString("NOT_FOUND_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reddit post not found..
        /// </summary>
        internal static string NOT_FOUND_REDDIT {
            get {
                return ResourceManager.GetString("NOT_FOUND_REDDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subreddit not found..
        /// </summary>
        internal static string NOT_FOUND_SUBREDDIT {
            get {
                return ResourceManager.GetString("NOT_FOUND_SUBREDDIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch channel is offline or was not found..
        /// </summary>
        internal static string NOT_FOUND_TWITCH {
            get {
                return ResourceManager.GetString("NOT_FOUND_TWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikipedia page not found..
        /// </summary>
        internal static string NOT_FOUND_WIKIPEDIA {
            get {
                return ResourceManager.GetString("NOT_FOUND_WIKIPEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timed out....
        /// </summary>
        internal static string REQUEST_TIMEOUT {
            get {
                return ResourceManager.GetString("REQUEST_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.gg/.
        /// </summary>
        internal static string URL_DISCORD {
            get {
                return ResourceManager.GetString("URL_DISCORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://images.google.com/searchbyimage?image_url={0}.
        /// </summary>
        internal static string URL_GOOGLE_IMAGE {
            get {
                return ResourceManager.GetString("URL_GOOGLE_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.ca/maps/@{0},{1},14z.
        /// </summary>
        internal static string URL_GOOGLE_MAPS {
            get {
                return ResourceManager.GetString("URL_GOOGLE_MAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://store.steampowered.com/app/{0}.
        /// </summary>
        internal static string URL_STEAM_APP {
            get {
                return ResourceManager.GetString("URL_STEAM_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam://connect/{0}:27015.
        /// </summary>
        internal static string URL_STEAM_CONNECT {
            get {
                return ResourceManager.GetString("URL_STEAM_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://steamcommunity.com/groups/.
        /// </summary>
        internal static string URL_STEAM_GROUP {
            get {
                return ResourceManager.GetString("URL_STEAM_GROUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://steamcommunity.com/id/.
        /// </summary>
        internal static string URL_STEAM_USER {
            get {
                return ResourceManager.GetString("URL_STEAM_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teamwork.tf/community/customserverlist/.
        /// </summary>
        internal static string URL_TEAMWORK_SERVERS {
            get {
                return ResourceManager.GetString("URL_TEAMWORK_SERVERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://wiki.teamfortress.com/wiki/{0}.
        /// </summary>
        internal static string URL_TF2_WIKI {
            get {
                return ResourceManager.GetString("URL_TF2_WIKI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.twitch.tv/.
        /// </summary>
        internal static string URL_TWITCH {
            get {
                return ResourceManager.GetString("URL_TWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/.
        /// </summary>
        internal static string URL_TWITTER {
            get {
                return ResourceManager.GetString("URL_TWITTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openweathermap.org/city/{0}.
        /// </summary>
        internal static string URL_WEATHER {
            get {
                return ResourceManager.GetString("URL_WEATHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/channel/.
        /// </summary>
        internal static string URL_YOUTUBE {
            get {
                return ResourceManager.GetString("URL_YOUTUBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: First time gifs take a few minutes to properly generate..
        /// </summary>
        internal static string WARN_GIF_LOADING {
            get {
                return ResourceManager.GetString("WARN_GIF_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume needs to be between 0 and 250% inclusive..
        /// </summary>
        internal static string WARN_VOICE_VOLUME {
            get {
                return ResourceManager.GetString("WARN_VOICE_VOLUME", resourceCulture);
            }
        }
    }
}
