site_name: FlawBOT
site_author: criticalflaw
theme:
    language: en
    name: material
    logo: resources/favicon.ico
    favicon: resources/favicon.ico
    features:
        - navigation.expand
    palette:
        - scheme: default
          primary: indigo
          accent: amber
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
        - scheme: slate
          primary: amber
          accent: orange
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
repo_name: GitHub
site_url: https://www.flawbot.criticalflaw.ca/
repo_url: https://github.com/CriticalFlaw/FlawBOT/
nav:
    - Home: 'index.md'
    - Installation: 'install.md'
    - Deployment: 'deploy.md'
    - Commands:
        - Bot: 'cmd/bot.md'
        - Channel: 'cmd/channel.md'
        - Emoji: 'cmd/emoji.md'
        - Games: 'cmd/games.md'
        - Misc: 'cmd/misc.md'
        - Music: 'cmd/music.md'
        - Role: 'cmd/role.md'
        - Search: 'cmd/search.md'
        - Server: 'cmd/server.md'
        - User: 'cmd/user.md'
hide:
    - toc
markdown_extensions:
    - admonition
    - pymdownx.superfences
    - toc:
        toc_depth: 0
plugins:
    - search
    - git-revision-date-localized:
        type: date
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/CriticalFlaw/FlawBOT
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/CriticalFlaw_
        - icon: fontawesome/brands/discord
          link: https://discord.gg/hTdtK9vBhE