site_name: FlawBOT
site_author: criticalflaw
site_url: criticalflaw.ca/FlawBOT
theme:
    language: en
    name: material
    logo: resources/favicon.ico
    favicon: resources/favicon.ico
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.sections
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections
        - navigation.expand
        - navigation.indexes
        - navigation.tracking
        - toc.integrate
        - header.autohide
        - content.tabs.link
        - search.suggest
        - search.highlight
    palette:
        - scheme: default
          primary: indigo
          accent: amber
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
        - scheme: slate
          primary: amber
          accent: orange
          toggle:
            icon: material/toggle-switch
            name: Switch to light mode
repo_name: GitHub
repo_url: https://github.com/CriticalFlaw/FlawBOT/
nav:
    - Home: 'index.md'
    - Tokens: 'tokens.md'
    - Deployment: 'deploy.md'
    - Lavalink: 'lavalink.md'
    - Commands:
        - Bot: 'modules/bot.md'
        - Channel: 'modules/channel.md'
        - Emoji: 'modules/emoji.md'
        - Games: 'modules/games.md'
        - Misc: 'modules/misc.md'
        - Music: 'modules/music.md'
        - Reddit: 'modules/reddit.md'
        - Role: 'modules/role.md'
        - Search: 'modules/search.md'
        - Server: 'modules/server.md'
        - Steam: 'modules/steam.md'
        - TF2: 'modules/tf2.md'
        - User: 'modules/user.md'
        - YouTube: 'modules/youtube.md'
    - Blog: 'https://criticalflaw.github.io/'
google_analytics:
    - G-Q532RTS1WC
    - auto
markdown_extensions:
    - admonition
    - pymdownx.superfences
    - toc:
        permalink: true
plugins:
    - search
    - git-revision-date-localized:
        type: date
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/CriticalFlaw/FlawBOT
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/CriticalFlaw_
        - icon: fontawesome/brands/discord
          link: https://discord.gg/hTdtK9vBhE
