//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlawBOT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlawBOT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel with the same name already exists..
        /// </summary>
        internal static string ERR_CHANNEL_EXISTS {
            get {
                return ResourceManager.GetString("ERR_CHANNEL_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be blank or over 100 characters..
        /// </summary>
        internal static string ERR_CHANNEL_NAME {
            get {
                return ResourceManager.GetString("ERR_CHANNEL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel topic must be less than 1024 characters long..
        /// </summary>
        internal static string ERR_CHANNEL_TOPIC {
            get {
                return ResourceManager.GetString("ERR_CHANNEL_TOPIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reach the Dog.CEO API..
        /// </summary>
        internal static string ERR_DOG_PHOTO {
            get {
                return ResourceManager.GetString("ERR_DOG_PHOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the server emoji. Either the HTTP request failed or Discord prevented the operation from completing..
        /// </summary>
        internal static string ERR_EMOJI_ADD {
            get {
                return ResourceManager.GetString("ERR_EMOJI_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a URL pointing to an emoji image or attach an image..
        /// </summary>
        internal static string ERR_EMOJI_IMAGE {
            get {
                return ResourceManager.GetString("ERR_EMOJI_IMAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server emoji name is invalid..
        /// </summary>
        internal static string ERR_EMOJI_NAME {
            get {
                return ResourceManager.GetString("ERR_EMOJI_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create the server emoji. Either the image size was too large..
        /// </summary>
        internal static string ERR_EMOJI_SIZE {
            get {
                return ResourceManager.GetString("ERR_EMOJI_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occurred: {0}.
        /// </summary>
        internal static string ERR_EXCEPTION {
            get {
                return ResourceManager.GetString("ERR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inner exception: {0}.
        /// </summary>
        internal static string ERR_EXCEPTION_INNER {
            get {
                return ResourceManager.GetString("ERR_EXCEPTION_INNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP address, please follow the format: `174.116.36.120`.
        /// </summary>
        internal static string ERR_INVALID_IP {
            get {
                return ResourceManager.GetString("ERR_INVALID_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid connection info, please follow the format: `174.116.36.120:27015; password hello`.
        /// </summary>
        internal static string ERR_INVALID_IP_GAME {
            get {
                return ResourceManager.GetString("ERR_INVALID_IP_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error calculating math equation, make sure your values are integers and the operation is valid!.
        /// </summary>
        internal static string ERR_MATH_EQUATION {
            get {
                return ResourceManager.GetString("ERR_MATH_EQUATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reach the NASA API..
        /// </summary>
        internal static string ERR_NASA_API {
            get {
                return ResourceManager.GetString("ERR_NASA_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating the Pokémon list: {0}.
        /// </summary>
        internal static string ERR_POKEMON_LIST {
            get {
                return ResourceManager.GetString("ERR_POKEMON_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a poll question..
        /// </summary>
        internal static string ERR_POLL_QUESTION {
            get {
                return ResourceManager.GetString("ERR_POLL_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Reddit category.
        /// </summary>
        internal static string ERR_REDDIT_UNKNOWN {
            get {
                return ResourceManager.GetString("ERR_REDDIT_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide more information on the issue (50 characters minimum)..
        /// </summary>
        internal static string ERR_REPORT_LENGTH {
            get {
                return ResourceManager.GetString("ERR_REPORT_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an existing server role..
        /// </summary>
        internal static string ERR_ROLE_EXISTING {
            get {
                return ResourceManager.GetString("ERR_ROLE_EXISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name cannot be blank..
        /// </summary>
        internal static string ERR_ROLE_NAME {
            get {
                return ResourceManager.GetString("ERR_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user doesn&apos;t have any roles..
        /// </summary>
        internal static string ERR_ROLE_NONE {
            get {
                return ResourceManager.GetString("ERR_ROLE_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are unauthorized to remove roles from this user..
        /// </summary>
        internal static string ERR_ROLE_NOT_ALLOWED {
            get {
                return ResourceManager.GetString("ERR_ROLE_NOT_ALLOWED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating Steam games list: {0}.
        /// </summary>
        internal static string ERR_STEAM_LIST {
            get {
                return ResourceManager.GetString("ERR_STEAM_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating TF2 item schema: {0}.
        /// </summary>
        internal static string ERR_TF2_LIST {
            get {
                return ResourceManager.GetString("ERR_TF2_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: First time gifs take a few minutes to properly generate..
        /// </summary>
        internal static string INFO_GIF_LOADING {
            get {
                return ResourceManager.GetString("INFO_GIF_LOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request timed out....
        /// </summary>
        internal static string INFO_REQ_TIMEOUT {
            get {
                return ResourceManager.GetString("INFO_REQ_TIMEOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond with **yes** to proceed or wait 10 seconds to cancel this operation..
        /// </summary>
        internal static string INFO_RESPOND {
            get {
                return ResourceManager.GetString("INFO_RESPOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutting Down....
        /// </summary>
        internal static string INFO_SHUTDOWN {
            get {
                return ResourceManager.GetString("INFO_SHUTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        internal static string NOT_FOUND_COMMON {
            get {
                return ResourceManager.GetString("NOT_FOUND_COMMON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emoji not found in the server list..
        /// </summary>
        internal static string NOT_FOUND_EMOJI {
            get {
                return ResourceManager.GetString("NOT_FOUND_EMOJI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location not found..
        /// </summary>
        internal static string NOT_FOUND_LOCATION {
            get {
                return ResourceManager.GetString("NOT_FOUND_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitch channel is offline or was not found..
        /// </summary>
        internal static string NOT_FOUND_TWITCH {
            get {
                return ResourceManager.GetString("NOT_FOUND_TWITCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wikipedia page not found..
        /// </summary>
        internal static string NOT_FOUND_WIKIPEDIA {
            get {
                return ResourceManager.GetString("NOT_FOUND_WIKIPEDIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.amiiboapi.com/api/amiibo/?name={0}.
        /// </summary>
        internal static string URL_Amiibo {
            get {
                return ResourceManager.GetString("URL_Amiibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/CriticalFlaw/FlawBOT/.
        /// </summary>
        internal static string URL_BOT_GitHub {
            get {
                return ResourceManager.GetString("URL_BOT_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discordapp.com/oauth2/authorize?client_id=339833029013012483&amp;scope=bot&amp;permissions=66186303.
        /// </summary>
        internal static string URL_BOT_Invite {
            get {
                return ResourceManager.GetString("URL_BOT_Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://catfact.ninja/fact.
        /// </summary>
        internal static string URL_CatFacts {
            get {
                return ResourceManager.GetString("URL_CatFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aws.random.cat/meow.
        /// </summary>
        internal static string URL_CatPhoto {
            get {
                return ResourceManager.GetString("URL_CatPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.urbandictionary.com/v0/define?term={0}.
        /// </summary>
        internal static string URL_Dictionary {
            get {
                return ResourceManager.GetString("URL_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.gg/.
        /// </summary>
        internal static string URL_Discord {
            get {
                return ResourceManager.GetString("URL_Discord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dog.ceo/api/breeds/image/random.
        /// </summary>
        internal static string URL_DogPhoto {
            get {
                return ResourceManager.GetString("URL_DogPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.ca/maps/@{0},{1},14z.
        /// </summary>
        internal static string URL_Google_Maps {
            get {
                return ResourceManager.GetString("URL_Google_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An image URL ending with .img, .png or .jpg is required!.
        /// </summary>
        internal static string URL_INVALID_IMG {
            get {
                return ResourceManager.GetString("URL_INVALID_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.ipstack.com/{0}?access_key=2e3dea495fa72127ed0f03ccb0b141b9&amp;format=1.
        /// </summary>
        internal static string URL_IPStack {
            get {
                return ResourceManager.GetString("URL_IPStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nasa.gov/planetary/apod?api_key={0}.
        /// </summary>
        internal static string URL_NASA {
            get {
                return ResourceManager.GetString("URL_NASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://newsapi.org/v2/everything?sources=google-news&amp;q={0}&amp;apiKey={1}.
        /// </summary>
        internal static string URL_News {
            get {
                return ResourceManager.GetString("URL_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.reddit.com/r/{0}/{1}.rss.
        /// </summary>
        internal static string URL_Reddit {
            get {
                return ResourceManager.GetString("URL_Reddit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.com/api/frames/{1}/{2}/3000/4000.
        /// </summary>
        internal static string URL_Simpsons_Frames {
            get {
                return ResourceManager.GetString("URL_Simpsons_Frames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.com/img/{1}/{2}.jpg.
        /// </summary>
        internal static string URL_Simpsons_Image {
            get {
                return ResourceManager.GetString("URL_Simpsons_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.com/api/random.
        /// </summary>
        internal static string URL_Simpsons_Random {
            get {
                return ResourceManager.GetString("URL_Simpsons_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}.com/gif/{1}/{2}/{3}.gif.
        /// </summary>
        internal static string URL_Simpsons_Result {
            get {
                return ResourceManager.GetString("URL_Simpsons_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.speedrun.com/api/v1/games?name={0}.
        /// </summary>
        internal static string URL_Speedrun {
            get {
                return ResourceManager.GetString("URL_Speedrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.speedrun.com/api/v1/{0}/{1}.
        /// </summary>
        internal static string URL_Speedrun_Extras {
            get {
                return ResourceManager.GetString("URL_Speedrun_Extras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://store.steampowered.com/app/{0}.
        /// </summary>
        internal static string URL_Steam_App {
            get {
                return ResourceManager.GetString("URL_Steam_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to steam://connect/{0}:27015.
        /// </summary>
        internal static string URL_Steam_Connect {
            get {
                return ResourceManager.GetString("URL_Steam_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://steamcommunity.com/groups/.
        /// </summary>
        internal static string URL_Steam_Group {
            get {
                return ResourceManager.GetString("URL_Steam_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://steamcommunity.com/id/.
        /// </summary>
        internal static string URL_Steam_User {
            get {
                return ResourceManager.GetString("URL_Steam_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teamwork.tf/community/customserverlist/.
        /// </summary>
        internal static string URL_TeamworkTF {
            get {
                return ResourceManager.GetString("URL_TeamworkTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://wiki.teamfortress.com/wiki/{0}.
        /// </summary>
        internal static string URL_TF2Wiki {
            get {
                return ResourceManager.GetString("URL_TF2Wiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.twitch.tv/.
        /// </summary>
        internal static string URL_Twitch {
            get {
                return ResourceManager.GetString("URL_Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://twitter.com/.
        /// </summary>
        internal static string URL_Twitter {
            get {
                return ResourceManager.GetString("URL_Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.weatherstack.com//current?access_key={0}&amp;query={1}.
        /// </summary>
        internal static string URL_Weather {
            get {
                return ResourceManager.GetString("URL_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/channel/{0}.
        /// </summary>
        internal static string URL_YouTube_Channel {
            get {
                return ResourceManager.GetString("URL_YouTube_Channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/playlist?list={0}.
        /// </summary>
        internal static string URL_YouTube_Playlist {
            get {
                return ResourceManager.GetString("URL_YouTube_Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.youtube.com/watch?v={0}.
        /// </summary>
        internal static string URL_YouTube_Video {
            get {
                return ResourceManager.GetString("URL_YouTube_Video", resourceCulture);
            }
        }
    }
}
