version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Restore packages
          command: cd src/FlawBOT && dotnet restore
      - run:
          name: Build App
          command: cd src/FlawBOT && dotnet build
      - run:
          name: Run App
          command: cd src/FlawBOT && dotnet run
