//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlawBOT.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlawBOT.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.amiiboapi.com/api/amiibo/.
        /// </summary>
        internal static string API_Amiibo {
            get {
                return ResourceManager.GetString("API_Amiibo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://catfact.ninja/fact.
        /// </summary>
        internal static string API_CatFacts {
            get {
                return ResourceManager.GetString("API_CatFacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://aws.random.cat/meow.
        /// </summary>
        internal static string API_CatPhoto {
            get {
                return ResourceManager.GetString("API_CatPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.urbandictionary.com/v0/define.
        /// </summary>
        internal static string API_Dictionary {
            get {
                return ResourceManager.GetString("API_Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dog.ceo/api/breeds/image/random.
        /// </summary>
        internal static string API_DogPhoto {
            get {
                return ResourceManager.GetString("API_DogPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://maps.googleapis.com/maps/api/geocode/json.
        /// </summary>
        internal static string API_Google_Geo {
            get {
                return ResourceManager.GetString("API_Google_Geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://maps.googleapis.com/maps/api/timezone/json.
        /// </summary>
        internal static string API_Google_Time {
            get {
                return ResourceManager.GetString("API_Google_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.openweathermap.org/data/2.5/weather.
        /// </summary>
        internal static string API_Google_Weather {
            get {
                return ResourceManager.GetString("API_Google_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.nasa.gov/planetary/apod.
        /// </summary>
        internal static string API_NASA {
            get {
                return ResourceManager.GetString("API_NASA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pokeapi.co/api/v2/pokemon/.
        /// </summary>
        internal static string API_Pokemon {
            get {
                return ResourceManager.GetString("API_Pokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.pokemontcg.io/v1/cards.
        /// </summary>
        internal static string API_PokemonTCG {
            get {
                return ResourceManager.GetString("API_PokemonTCG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.kuroganehammer.com/api/characters/.
        /// </summary>
        internal static string API_SmashBros {
            get {
                return ResourceManager.GetString("API_SmashBros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.speedrun.com/api/v1/.
        /// </summary>
        internal static string API_Speedrun {
            get {
                return ResourceManager.GetString("API_Speedrun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.steampowered.com/ISteamApps/GetAppList/v0002/.
        /// </summary>
        internal static string API_SteamGames {
            get {
                return ResourceManager.GetString("API_SteamGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teamwork.tf/api/v1/.
        /// </summary>
        internal static string API_TeamworkTF {
            get {
                return ResourceManager.GetString("API_TeamworkTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.trade.tf/api/schema_440.json.
        /// </summary>
        internal static string API_TradeTF {
            get {
                return ResourceManager.GetString("API_TradeTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/streams/.
        /// </summary>
        internal static string API_Twitch {
            get {
                return ResourceManager.GetString("API_Twitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org//w/api.php?action=query&amp;format=json&amp;prop=info&amp;redirects=1&amp;formatversion=2&amp;inprop=url.
        /// </summary>
        internal static string API_Wikipedia {
            get {
                return ResourceManager.GetString("API_Wikipedia", resourceCulture);
            }
        }
    }
}
